services:
    app.image_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%uploads_directory%']

    app.doctrine_image_upload_listener:
        class: AppBundle\EventListener\ImageUploadListener
        arguments: ['@app.image_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: preRemove }
